name: Code Quality

on:
  push:
    branches: ['test-build', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ricardochaves/python-lint@v1.4.0
   
