name: Code Quality

on:
  push:
    branches: ['test-build', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Code Quality and Lint
    # You may pin to the exact commit or the version.
    # uses: ricardochaves/python-lint@32032eca67291cd71f88d79e61bc4b904ee03265
      uses: ricardochaves/python-lint@v1.3.0
      with:
        # A list of all paths to test
        python-root-list: "."
        # Use Pylint
        use-pylint: true
        # Use pycodestyle
        use-pycodestyle: false
        # Use Flake8
        use-flake8: true
        # Use Black
        use-black: true
        # Use mypy
        use-mypy: true
        # Use isort
        use-isort: true
        # Extra options: pylint $(extra-pylint-options) $(python-root-list)
        # extra-pylint-options: # optional, default is 
        # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
        # extra-pycodestyle-options: # optional, default is 
        # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
        # extra-flake8-options: # optional, default is 
        # Extra options: black --check $(extra-black-options) $(python-root-list)
        # extra-black-options: # optional, default is 
        # Extra options: mypy $(extra-mypy-options) $(python-root-list)
        # extra-mypy-options: # optional, default is 
        # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
        # extra-isort-options: # optional, default is 
